services:
  api:
    build:
      context: .
      target: prod
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:8.2-rc1-alpine3.22
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    env_file: .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  mongo:
    image: mongo
    env_file: .env
    ports:
    - "27017:27017"

  postgres:
    image: postgres:13.22-alpine3.22
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
    - "5432:5432"

volumes:
  redis-data:
  pgdata:
