services:
  api:
    build:
      context: .
      target: prod
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:8.2-rc1-alpine3.22
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    env_file: .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  mongo:
    image: mongo
    env_file: .env
    ports:
    - "27017:27017"

volumes:
  redis-data:
