import { randomBytes } from 'crypto'

import { IRefreshSecretGenerator } from '@application/ports/refresh-secret-generator.js'
import { PlainRefreshSecret } from '@domain/value-objects/plain-refresh-secret.js'

type RandomBytesLike = typeof randomBytes

/**
 * RefreshSecretGenerator produces cryptographically secure random refresh secrets.
 * @param {RandomBytesLike} generator Function used to generate secure random bytes (defaults to crypto.randomBytes).
 */
export class RefreshSecretGenerator implements IRefreshSecretGenerator {
  constructor(private readonly generator: RandomBytesLike = randomBytes) {}

  /**
   * Generates a new refresh secret using cryptographically secure random bytes.
   * @param {number} length Number of random bytes to generate.
   * @returns {PlainRefreshSecret} A PlainRefreshSecret created from the generated bytes.
   */
  generate(length: number): PlainRefreshSecret {
    return PlainRefreshSecret.fromBytes(this.generator(length))
  }
}
